### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by lostcup** [crhan/ZhongHongHVAC#1]
I just installed Hassos with most recent preview version 3.3 on my Pi 3B+.

After add zhong_hong in configuration.yaml. I got following error in log:

> 2019-07-20 14:56:22 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform zhong_hong
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
>     SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/components/zhong_hong/climate.py", line 48, in setup_platform
>     for (addr_out, addr_in) in hub.discovery_ac()
>   File "/usr/local/lib/python3.7/site-packages/zhong_hong_hvac/hub.py", line 191, in discovery_ac
>     self.open_socket()
>   File "/usr/local/lib/python3.7/site-packages/zhong_hong_hvac/hub.py", line 50, in open_socket
>     self.sock = self.__get_socket()
>   File "/usr/local/lib/python3.7/site-packages/zhong_hong_hvac/hub.py", line 41, in __get_socket
>     s.connect((self.ip_addr, self.port))
> ConnectionRefusedError: [Errno 111] Connection refused

I'm sure IP address is correct. Pls help check how to correct this error. Thank you!

**Comment by crhan** [comment]
close old issue
