### ISSUE TITLE
module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by leoujz** [crhan/ZhongHongHVAC#2]
run in python 3.10, it reports module 'collections' has no attribute 'Iterable'. 
To solve the problem, replace `class AcData(collections.Iterable)` in line 219 of protocol.py
with `class AcData(collections.abc.Iterable)`, 
and it runs fine

**Comment by crhan** [comment]
version bump to 1.0.10 and uploaded to pypi, thanks
